FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \

    # basic graphics runtime dependencies
    libxcb-cursor0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-xinerama0 \
    libxcb-xkb1 \
    libxkbcommon-x11-0 \
    libdbus-1-3 \
    libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxkbcommon-dev \

    # development tools
    build-essential cmake ninja-build \
    libvulkan-dev \
    libqt6opengl6-dev \
    qt6-base-dev \
    qt6-declarative-dev \
    qml6-module-qtquick \
    qml6-module-qtquick-controls \
    qml6-module-qtquick-layouts \
    qml6-module-qtquick-templates \
    qml6-module-qtquick-window \
    qml6-module-qtqml-workerscript \

    # testing tools
    libgtest-dev clang-tidy cppcheck \

    # clean cache
    && apt-get clean && rm -rf /var/lib/apt/lists/*